name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'v[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install --ignore-scripts
    - run: echo "$PWD/node_modules/.bin" >> "$GITHUB_PATH"
    - run: deno test --no-run
    - run: deno lint

    - run: src/cli.ts
    - run: lib/cli.js --outDir nodejs/
    - run: git diff --no-index lib/ nodejs/

    - run: deno test --allow-read=. src/
    - run: node --test lib/
