name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: echo "$PWD/node_modules/.bin" >> $GITHUB_PATH
    - run: deno lint
    - run: deno fmt --check
    - run: deno cache src/cli.ts
    - run: deno vendor src/deps.vendor.ts --output src/vendor/
    - name: Create Node.js build using Deno
      run: |
        npm run build
        mv lib/ lib_by_deno
    - run: ./src/cli.ts --version
    - run: ./lib_by_deno/cli.js --version
    - name: Recreate Node.js build using Node.js
      run: |
        ./lib_by_deno/cli.js tsconfig.json
        mv lib/ lib_by_nodejs
    - name: Compare the builds
      run: git diff --no-index lib_by_deno/ lib_by_nodejs/
