name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: denolib/setup-deno@v2
    - uses: actions/checkout@v2
    - run: deno lint --unstable

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: denolib/setup-deno@v2
    - uses: actions/checkout@v2
    - run: deno fmt --check

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: denolib/setup-deno@v2
    - uses: actions/checkout@v2
    - run : npm ci --ignore-scripts
    - name: Create Node.js build using Deno
      run: |
        npm run prepare
        mv lib/ lib_by_deno
    - name: Recreate Node.js build using Node.js
      run: |
        node lib_by_deno/cli.js src/tsconfig.json
        mv lib/ lib_by_nodejs
    - name: Compare the builds
      run: git diff --no-index lib_by_deno/ lib_by_nodejs/
